# Generated by Django 4.1 on 2022-09-29 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_entregable_estudiate_profesor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='estudiate',
            new_name='estudiante',
        ),
    ]
